version: '3'

services:
  backend:
    container_name: 'k-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'k-database'
    image: postgres:12.12-alpine
    restart: always
    env_file: .env
    volumes:
      - "pg-data:/var/lib/postgresql/data/pgdata"

  frontend:
    container_name: 'k-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
